### ISSUE TITLE
Fix Syntax-Error message

### ISSUE THREAD

**Issue by Pascalmh** [webSPELL/webSPELL#140]
The output of `function system_error()` should be changed to the BS3-Style - also the <head> section should be updated.

**Comment by DDaems** [comment]
I could put it in a panel or alert and center it with flexbox.
Like i did on the checklogin.

but unfortunatly i have not enough knowledge of php.
on how to include this in the die statement.

```
    <base href="<?php echo $rewriteBase; ?>">
    <?php foreach ($components['css'] as $component) {
        echo '<link href="' . $component . '" rel="stylesheet">';}
```
Some help that points me in the right direction is much appriciated.

**Comment by b1u3** [comment]
- hard-coded BS include
- output-buffering

**Comment by derchrisuk** [comment]
I'm currently looking at the `system_error`.
Can think of 2x different scenarios here.
Either there is an error, before it will hit any other code, like no MySQL connection, or banned.
Or there is an error somewhere after part of the site has been rendered, like missing MySQL tables/columns, src include not working or invalid request.

Which would lead to 2x different style layout.
Where currently we post a "full" HTML body regardless of where the error is originating from.

I will try to create some new code to cover for both.
Alternatively we could redirect any error to a blank new page.
Which personally I would prefer, because an error should be clearly visible, and stop the page from rendering anything.

**Comment by Phhere** [comment]
Since we are using output buffering you can just throw away the available buffer and clear the page to generate an blank new page
