### ISSUE TITLE
webSPELL Security Vulnerability Notification

### ISSUE THREAD

**Issue by HTBridge** [webSPELL/webSPELL#309]
Hello,

High-Tech Bridge Security Research Lab has a discovered security vulnerability in webSPELL.

Preview available here: https://www.htbridge.com/advisory/HTB23291

Developers can contact us by email for details: advisory (at) htbridge.com

For any questions related to this notification message - please visit our General Information & Disclosure Policy page: https://www.htbridge.com/advisory/disclosure_policy.html [^]

Best regards,
High-Tech Bridge Security Research Lab

**Comment by Getschonnik** [comment]
This applies to version 4.2.4. If the problem existiert with 4.3.0 too ?

**Comment by HTBridge** [comment]
Hello, yes, vulnerability exist.

**Comment by Getschonnik** [comment]
This is a beta. Can you provide details of where about the problem is, so that other programmers can take care of it? 

Once someone has solved this, a PullRequest can here be created so that developers fill the gaps. 
Or has the developer you already contacted?

PS: Currently we work with this beta and so we are interested too where the problem is.

**Comment by HTBridge** [comment]
Details was submitted via contact form and to emails on webspell.org domain, but no replies was received according this vulnerability.

**Comment by Pascalmh** [comment]
@HTBridge thank you for the report! We are working on a fix!

**Comment by derchrisuk** [comment]
Merged into new 4.2.5 release
